export const staticProjects = [
  {
    id: "p1",
    title: "Chale Fir",
    category: "Cinematography",
    year: "2025",
    description: "An immersive journey through the streets of Dakor, capturing the essence of friendship and the fluid transitions of life in motion. This project explores the rhythmic patterns of local life through a series of carefully orchestrated camera movements and natural lighting.",
    src: "/project/lv_0_20250730175624.mp4",
    type: "video",
  },
  {
    id: "p2",
    title: "Dakor Temple",
    category: "Street Film",
    year: "2025",
    description: "A spiritual exploration of the Dakor Temple, focusing on the interplay between sacred architecture and the vibrant human devotion it houses. This film serves as a visual meditation on religious heritage and the timeless traditions that define the local cultural landscape.",
    src: "/project/lv_0_20250815211113.mp4",
    type: "video",
  },
  {
    id: "p3",
    title: "The Last Day",
    category: "Experimental",
    year: "2026",
    description: "A short cinematic essay by Ayush Mistry that delves into the fleeting nature of time and memory. Using high-contrast lighting and abstract compositions, this experimental piece challenges the viewer's perception of reality and the emotional weight of finality.",
    src: "/project/the-last-day.mp4",
    type: "video",
    poster: "/gallery/IMG_20260329_144845047_HDR.jpg.jpeg",
  },
  {
    id: "p4",
    title: "The Nature",
    category: "Landscape",
    year: "2026",
    description: "Dawn light across ridgelines — a study in negative space and atmosphere. This series captures the silent conversation between the earth and the first light of day, highlighting the minimalist beauty of untouched terrains and the ephemeral quality of mountain mists.",
    src: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80",
    type: "image",
  },
  {
    id: "p5",
    title: "Urban Pulse",
    category: "Editorial",
    year: "2025",
    description: "Night geometry and reflections in the city core. This project examines the architectural symmetry of modern urban environments under the cloak of night, where artificial light creates a new, cinematic reality through glass, steel, and shadow.",
    src: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=1600&q=80",
    type: "image",
  },
  {
    id: "p6",
    title: "Coastal Drift",
    category: "Seascape",
    year: "2024",
    description: "Long exposures where tide and sky merge into one tone. A visual exploration of the horizon line and the meditative quality of the ocean, using extended shutter speeds to transform chaotic waves into ethereal, painterly textures.",
    src: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?auto=format&fit=crop&w=1600&q=80",
    type: "image",
  },
];

export const staticGallery = [
  {
    id: "fg1",
    category: "Landscape",
    src: "/image-1.jpg",
    span: "tall",
    caption: "Muted ridgelines under absolute calm.",
    type: "image",
  },
  {
    id: "fg2",
    category: "Editorial",
    src: "/image-2.jpg",
    span: "normal",
    caption: "Contrast study in studio light.",
    type: "image",
  },
  {
    id: "fg3",
    category: "Portrait",
    src: "/image-3.jpg",
    span: "wide",
    caption: "Intertwined shadows and quiet focus.",
    type: "image",
  },
  {
    id: "fg4",
    category: "Landscape",
    src: "/image-4.jpg",
    span: "tall",
    caption: "The rhythm of tides at twilight.",
    type: "image",
  },
  {
    id: "fg5",
    category: "Portrait",
    src: "/image-5.jpg",
    span: "large",
    caption: "Warm silhouettes on alabaster stone.",
    type: "image",
  },
  {
    id: "fg6",
    category: "Editorial",
    src: "/image-6.jpg",
    span: "normal",
    caption: "Restraint and shadow play.",
    type: "image",
  },
  {
    id: "fg7",
    category: "Cinematography",
    src: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=1600&q=80",
    span: "wide",
    caption: "Urban geometry at midnight.",
    type: "image",
  },
  {
    id: "fg8",
    category: "Landscape",
    src: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80",
    span: "tall",
    caption: "Negative space in high altitudes.",
    type: "image",
  }
];
